/*!
 * Nhac Web Karaoke code for JW7 v1.0.0 support BigData
 * Copyright 2017 Nhac.vn, Vega Corp
 * Dev by Tan Vu ™
 * http://nhac.vn - 2017-09-19
 */
function GoPerformance(d,b,U){function O(){b.performance&&"undefined"!==typeof J&&"function"===typeof J&&(e=new Date,"playing"==d.getState()?(t+=(e-g)/1E3,k.playing=Math.round(t),0==n&&(h.play=++n),0==u&&0<v&&(h.pause=++u)):"paused"==d.getState()?(v+=(e-g)/1E3,k.pause=Math.round(v),0==u&&(h.pause=++u),0==n&&0<t&&(h.play=++n)):"buffering"==d.getState()&&(w+=(e-g)/1E3,k.buffer=Math.round(w),0==n&&(h.play=n)),e=new Date,l[f]+=Math.round((e-r)/1E3),r=new Date,J(),P())}function P(){g=new Date;v=t=w=0;
k={error:0,idle:0,buffer:0,playing:0,pause:0};K=L=M=n=u=N=0;h={seek:0,pause:0,play:0,user_change_profile:0,auto_change_profile:0,change_caption:0};for(var a in l)l[a]=0}function T(){z||(Q=1);for(var a in R){var b=R[a];if(b.r.test(p)){x=b.s;break}}/Windows/.test(x)&&(m=/Windows (.*)/.exec(x)[1],x="Windows");switch(x){case "Mac OS X":m=/Mac OS X (10[\.\_\d]+)/.exec(p)[1];break;case "Android":m=/Android ([\.\_\d]+)/.exec(p)[1];break;case "iOS":m=/OS (\d+)_(\d+)_?(\d+)?/.exec(nVer),m=m[1]+"."+m[2]+"."+
(m[3]|0)}a=p.match(/(opera|chrome|safari|firefox|msie|trident(?=\/))\/?\s*(\d+)/i)||[];if(/trident/i.test(a[1])){var c=/\brv[ :]+(\d+)/g.exec(p)||[];return"IE "+(c[1]||"")}if("Chrome"===a[1]&&(c=p.match(/\b(OPR|Edge)\/(\d+)/),null!=c))return c.slice(1).join(" ").replace("OPR","Opera");a=a[2]?[a[1],a[2]]:[navigator.appName,navigator.appVersion,"-?"];null!=(c=p.match(/version\/(\d+)/i))&&a.splice(1,1,c[1]);E=a[0].toLowerCase();S=a[1]}function J(){b.perform_debug&&console.log("Performance::",b,E,typeof d.duration,
typeof d.getDuration,d.getDuration());if(void 0==E||0>F)"function"===typeof d.duration&&0<d.duration()?F=Math.round(d.duration()):"function"===typeof d.getDuration&&0<d.getDuration()&&(F=Math.round(d.getDuration())),T();Number.prototype.padLeft=function(a,b){var c=String(a||10).length-String(this).length+1;return 0<c?Array(c).join(b||"0")+this:this};var a=new Date,f=[a.getFullYear(),(a.getMonth()+1).padLeft(),a.getDate().padLeft()].join("-")+" "+[a.getHours().padLeft(),a.getMinutes().padLeft(),a.getSeconds().padLeft()].join(":");
a=Math.round(a.getTime()/1E3);var e=-1;"function"===typeof d.currentTime?e=Math.round(d.currentTime()):"function"===typeof d.getPosition&&(e=Math.round(d.getPosition()));c.ctime=a;c.du=G;c.uid=b.user_id;c.vid=b.vega_id;c.msi=b.msisdn;c.pid=b.package_id;c.cid=b.content_id;c.aid=b.album_id;c.ctype=b.content_type;c.uso=b.utm_source;c.ume=b.utm_medium;c.ute=b.utm_term;c.uco=b.utm_content;c.uca=b.utm_campaign;c.em=Q;c.pst=k;c.event=h;c.pro=l;c.pos=e;c.dti=F;c.os=x.toLowerCase();c.osv=m;c.br=E;c.brv=S;
c.did=b.device_id;c.c=b.channel;c.s=b.session_id;c.ua=p;c.url=A;c.ref=b.url_referer;c.act=b.action_type;c.ptype=b.player_type;c.sid=b.service_id;c.sr=b.source_rec;c.lst="online";c.o=b.other_info;c.etime=b.expired_time;c.cstr=f;c.v=b.version;f=btoa(JSON.stringify(c));b.perform_debug&&(console.log("player_states:::",k),console.log("events::::::::::",h),console.log("profiles_time:::",l),console.log("datas:::::::::::",c));f="https://collect.ovp.vn/nhac_collect?data="+f;window.jQuery?$.get(f,function(a,
b){}):(a=new XMLHttpRequest,a.open("GET",f,!1),a.send(null))}var A,y,B,z=!1,C="",R=[{s:"Windows 10",r:/(Windows 10.0|Windows NT 10.0)/},{s:"Windows 8.1",r:/(Windows 8.1|Windows NT 6.3)/},{s:"Windows 8",r:/(Windows 8|Windows NT 6.2)/},{s:"Windows 7",r:/(Windows 7|Windows NT 6.1)/},{s:"Windows Vista",r:/Windows NT 6.0/},{s:"Windows Server 2003",r:/Windows NT 5.2/},{s:"Windows XP",r:/(Windows NT 5.1|Windows XP)/},{s:"Windows 2000",r:/(Windows NT 5.0|Windows 2000)/},{s:"Windows ME",r:/(Win 9x 4.90|Windows ME)/},
{s:"Windows 98",r:/(Windows 98|Win98)/},{s:"Windows 95",r:/(Windows 95|Win95|Windows_95)/},{s:"Windows NT 4.0",r:/(Windows NT 4.0|WinNT4.0|WinNT|Windows NT)/},{s:"Windows CE",r:/Windows CE/},{s:"Windows 3.11",r:/Win16/},{s:"Android",r:/Android/},{s:"Open BSD",r:/OpenBSD/},{s:"Sun OS",r:/SunOS/},{s:"Linux",r:/(Linux|X11)/},{s:"iOS",r:/(iPhone|iPad|iPod)/},{s:"Mac OS X",r:/Mac OS X/},{s:"Mac OS",r:/(MacPPC|MacIntel|Mac_PowerPC|Macintosh)/},{s:"QNX",r:/QNX/},{s:"UNIX",r:/UNIX/},{s:"BeOS",r:/BeOS/},{s:"OS/2",
r:/OS\/2/},{s:"Search Bot",r:/(nuhk|Googlebot|Yammybot|Openbot|Slurp|MSNBot|Ask Jeeves\/Teoma|ia_archiver)/}],Q=0,F=-1,p=navigator.userAgent,x="unknown",m="unknown",E,S,c={},D=0,H=!1,I=!1,q,G=60,k={},h={},l={},w=0,t=0,v=0,r,g=new Date,e,N=0,u=0,n=0,M=0,L=0,K=0,f;d.onReady(function(a){b.perform_debug&&console.log("onReady::::::::",b,d.getConfig());k.error=0;0<b.duration&&(G=b.duration);q=setInterval(O,1E3*G);b.perform_debug&&console.log("CheckHost::",A,y,B,z,C);A=document.URL;y=window.location!=window.parent.location?
window.parent.location:document.location;"undefined"==y&&(y=A);B=y.hostname;0<=B.indexOf("nhac.vn")?(z=!0,void 0!=b&&void 0!=b.mode&&(C=b.mode)):(z=!1,C=0<B.indexOf("?embed=1")?"iframe":"embed");b.modepro=C;b.perform_debug&&console.log("CheckHost::onsite",A,"referrer:",y,"domainReferrer:",B,"hostmode:",z,"mode:",C,"config.mode:",b.mode,"config.modepro:",b.modepro)});d.on("meta",function(a){e=new Date;b.perform_debug&&console.log("onMeta:::::::::duration",a.duration,a.type,a.width,a.height,d.getState(),
g.getTime(),e.getTime(),e-g)});d.on("firstFrame",function(a){e=new Date;b.perform_debug&&console.log("onFirstFrame:::loadTime/type",a.loadTime,a.type,d.getState(),g.getTime(),e.getTime(),e-g);w+=(e-g)/1E3;g=new Date;H=!0});d.on("buffer",function(a){e=new Date;b.perform_debug&&console.log("onBuffer:::::::oldstate",a.oldstate,g.getTime(),e.getTime(),e-g);"idle"==a.oldstate&&(k.idle=Math.round((e-g)/1E3));g=new Date});d.on("pause",function(a){I?(I=!1,d.play(!0)):(e=new Date,b.perform_debug&&console.log("onPaused:::::::oldstate",
a.oldstate,g.getTime(),e.getTime(),e-g),"playing"==a.oldstate&&(t+=(e-g)/1E3,k.playing=Math.round(t)),g=new Date,h.pause=++u)});d.on("play",function(a){e=new Date;b.perform_debug&&console.log("onPlay:::::::::oldstate",a.oldstate,d.getState(),g.getTime(),e.getTime(),e-g);"buffering"==a.oldstate?(w+=(e-g)/1E3,k.buffer=Math.round(w)):"paused"==a.oldstate&&(v+=(e-g)/1E3,k.pause=Math.round(v));g=new Date;h.play=++n});d.on("playlistItem",function(a){b.perform_debug&&(console.log("playlistItem:::::::::evt",
a,a.item,a.item.mediaid,b.content_id,b.content_type),console.log("playlistItem:::::::::perform",q,H,b.content_id,a.item.mediaid));if(void 0===b.content_id||"album"===b.content_type)b.content_id=a.item.mediaid;void 0!=q&&H&&(clearInterval(q),P(),q=setInterval(O,1E3*G))});d.on("seek",function(a){b.perform_debug&&console.log("onSeek:::::::::evt",a,N);h.seek=++N});d.on("levels",function(a){var c=a.levels;b.perform_debug&&console.log("levels:::::::::",D,a.currentQuality,a,c);for(var e=0;e<c.length;e++){var g=
c[e].label;g.toLowerCase().indexOf("k");"Auto"!=g&&(g=g.replace("p",""),g=g.replace("k",""),g=g.replace("K",""),l[g]=0)}D=a.currentQuality;if(void 0==f||0==d.getPosition())r=new Date;f=c[a.currentQuality].label;f=f.replace("p","");f=f.replace("k","");f=f.replace("K","")});d.on("visualQuality",function(a){b.perform_debug&&console.log("visualQuality::evt",a,L);h.auto_change_profile=++L;void 0!=f&&0!=d.getPosition()&&(e=new Date,l[f]+=Math.round((e-r)/1E3));r=new Date;f=d.getQualityLevels()[a.level.index].label;
f=f.replace("p","");f=f.replace("k","");f=f.replace("K","")});d.on("levelsChanged",function(a){var c=a.levels,g=c[0].label;("Auto"==g||"T\u1ef1 \u0111\u1ed9ng"==g)&&H&&(0<a.currentQuality&&a.currentQuality<D||0==D)&&(I=!0,d.pause(!0));b.perform_debug&&console.log("levelsChanged:::::::::evt",a,M,I,a.currentQuality,c.length);h.user_change_profile=++M;void 0!=f&&(e=new Date,l[f]+=Math.round((e-r)/1E3),r=new Date);a.currentQuality>=c.length||(f=c[a.currentQuality].label,"Auto"!=f&&(f=f.replace("p",""),
f=f.replace("k",""),f=f.replace("K","")),D=a.currentQuality)});d.on("captionsChanged",function(a){b.perform_debug&&console.log("captionsChanged:::::::::evt",a,K,d.getPosition());0<d.getPosition()&&(h.change_caption=++K)});d.on("complete",function(a){b.perform_debug&&console.log("complete",typeof nextUp,q,b.content_type);void 0!=q&&clearInterval(q)});this.resize=function(a,b){}};